# -*- coding: utf-8 -*-
"""5_Clara Jessica_26040027_9 April

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3Ruvaw3sGncHj8IvVENPcc9warQS5Il
"""

# ========================================
# SECTION 1 PROJECT SETUP
# ========================================

print("=" * 40)
print(" OpenTrack — Open Source Project")
print(" Project Lead : Clara Jessica")
print("=" * 40)

project = ("OpenTrack", "1.0", 2024, "Python", "Clara Jessica")

print("Name:", project[0])
print("Version:", project[1])
print("First 3 fields:", project[:3])
print("Language count:", project.count("Python"))
print("Language index:", project.index("Python"))

# project[0] = "test" -> TypeError (immutable)


# ========================================
# SECTION 1 CONTRIBUTORS
# ========================================

contributors = []

for i in range(4):

    while True:
        name = input("name: ")
        if name.replace(" ", "").isalpha():
            break
        else:
            print("invalid name")

    while True:
        role = input("role: ")
        if role != "":
            break

    while True:
        lang = input("language: ")
        if lang.replace(" ", "").isalpha():
            break

    while True:
        commits = input("commits: ")
        if commits.isdigit():
            commits = int(commits)
            break
        else:
            print("invalid number")

    while True:
        country = input("country: ")
        if country.replace(" ", "").isalpha():
            break

    contributor = {
        "name": name,
        "role": role,
        "language": lang,
        "commits": commits,
        "country": country
    }

    contributors.append(contributor)

names = []
for c in contributors:
    names.append(c["name"])

names.sort()

print("Sorted names:", names)
print("Last name:", names[-1])
print("First two:", names[:2])

for c in contributors:
    c.update({"status": "Active"})

print("Contributor 1 status:", contributors[0].get("status"))

backup = contributors[0].copy()
print("Backup:", backup)


# ========================================
# SECTION 2 ISSUES
# ========================================

issues = []

for i in range(5):

    while True:
        issue_id = input("id: ")
        if issue_id == "":
            print("invalid id")
            continue
        if issue_id not in [x["id"] for x in issues]:
            break
        else:
            print("duplicate id not allowed")

    while True:
        title = input("title: ")
        if title != "":
            break

    while True:
        issue_type = input("type (Bug/Feature): ").lower()
        if issue_type in ["bug", "feature"]:
            break
        else:
            print("invalid type")

    while True:
        priority = input("priority (Critical/High/Medium/Low): ").capitalize()
        if priority in ["Critical", "High", "Medium", "Low"]:
            break
        else:
            print("invalid priority")

    while True:
        reporter = input("reporter: ")
        if reporter.replace(" ", "").isalpha():
            break

    while True:
        status = input("status (Open/In Progress/Resolved): ").title()
        if status in ["Open", "In Progress", "Resolved"]:
            break
        else:
            print("invalid status")

    issue = {
        "id": issue_id,
        "title": title,
        "type": issue_type,
        "priority": priority,
        "reporter": reporter,
        "status": status
    }

    issues.append(issue)

open_count = 0
for i in issues:
    if i["status"] == "Open":
        open_count += 1

print("Open issues:", open_count)

issues[0]["priority"] = "Critical"

print("Last two issues:", issues[-2:])


# ========================================
# SECTION 2 SET OPERATIONS
# ========================================

reporters = set()
tech_stack = set()

for i in issues:
    reporters.add(i["reporter"])

for c in contributors:
    tech_stack.add(c["language"])

reporters.add("Go")
tech_stack.discard("Rust")

print("Union:", reporters.union(tech_stack))
print("Intersection:", reporters.intersection(tech_stack))
print("Difference:", reporters.difference(tech_stack))

if "Critical" in {"Critical", "High", "Medium", "Low"}:
    print("Critical present : YES — flag for immediate review.")


# ========================================
# SECTION 2 DICTIONARY ANALYSIS
# ========================================

priority_count = {}

for i in issues:
    p = i["priority"]
    if p in priority_count:
        priority_count[p] += 1
    else:
        priority_count[p] = 1

print("Keys:", priority_count.keys())
print("Values:", priority_count.values())

for k, v in priority_count.items():
    print(k, v)

status_groups = {}

for i in issues:
    s = i["status"]
    if s not in status_groups:
        status_groups[s] = []
    status_groups[s].append(i["title"])

print("Status groups:", status_groups)

report_count = {}

for i in issues:
    r = i["reporter"]
    if r in report_count:
        report_count[r] += 1
    else:
        report_count[r] = 1

top = ""
max_count = 0

for k in report_count:
    if report_count[k] > max_count:
        max_count = report_count[k]
        top = k

print("Top reporter:", top, max_count)

removed = issues[0].pop("type")
print("Removed:", removed)
print("Updated issue:", issues[0])


# ========================================
# SECTION 3 FILE HANDLING
# ========================================

import os

folder = "open_track"

if not os.path.exists(folder):
    os.mkdir(folder)

report_path = os.path.join(folder, "project_report.txt")
csv_path = os.path.join(folder, "issues.csv")

try:
    f = open(report_path, "w")
    f.write("Project Report\n")
    f.write(str(project) + "\n")
    f.write(str(contributors) + "\n")
    f.write(str(issues) + "\n")
    f.close()
except IOError:
    print("write error")

try:
    f = open(csv_path, "w")
    f.write("id,title,priority,reporter,status\n")
    for i in issues:
        f.write(f"{i['id']},{i['title']},{i['priority']},{i['reporter']},{i['status']}\n")
    f.close()
except IOError:
    print("csv error")

try:
    f = open(report_path, "r")
    print(f.read())
    f.close()
except FileNotFoundError:
    print("file not found")


# ========================================
# BONUS
# ========================================

urgent = [i["title"] for i in issues if i["priority"] in ["Critical", "High"]]

print("Urgent:", urgent)
print("Count:", len(urgent))

f = open(report_path, "a")
f.write("\nURGENT ISSUES\n")

for u in urgent:
    f.write(u + "\n")

f.close()

f = open(report_path, "r")
lines = f.readlines()

print("Last 6 lines:", lines[-6:])

f.close()